version: '3'
 
services:
  regalunos:

    container_name: sconsultar_alunos

    build:
      context: Base/Classes
      dockerfile: Dockerfile
      args:
        FLASK_APP: ConsAlunos.py
 
    ports:
      - 5000:5000

    depends_on:
      - db
 
    environment:
        MYSQL_PASSWORD: 'root'

    networks:
      - redecomum
  db:
    container_name: db

    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - 6000:3306
    
    volumes:
      - db:/var/lib/mysql
      - ./DataBase/tabelas.sql:/data/application/tabelas.sql
    

    networks:
      - redecomum

networks:
  redecomum:

volumes:
  db: