version: '3'

services:

  consalunos:

    container_name: sconsultar_alunos

    build:
      context: Base/Classes
      dockerfile: DockerfileConsAlunos
      args:
        FLASK_APP: ConsAlunos.py
 
    ports:
      - 5000:5000

    depends_on:
      - dbAlunos
 
    environment:
        MYSQL_PASSWORD: 'root'

    networks:
      - redecomum

#-------------------------------------------------------------------------------------------------------------

  autuser:
    container_name: autenticar_usuarios

    build:
      context: Base/Classes
      dockerfile: DockerfileAutUser
      args:
        FLASK_APP: AutUser.py

    ports:
      - 5001:5000

    depends_on:
      - db
 
    environment:
        MYSQL_PASSWORD: 'root'

    networks:
      - redecomum

#-------------------------------------------------------------------------------------------------------------

  regalunos:
    container_name: registrar_alunos

    build:
      context: Base/Classes
      dockerfile: DockerfileRegAlunos
      args:
        FLASK_APP: RegAlunos.py

    ports:
      - 5002:5000

    depends_on:
      - dbAlunos
 
    environment:
        MYSQL_PASSWORD: 'root'

    networks:
      - redecomum

#-------------------------------------------------------------------------------------------------------------

  regdisciplinas:
    container_name: registrar_disciplinas

    build:
      context: Base/Classes
      dockerfile: DockerfileRegDisciplinas
      args:
        FLASK_APP: RegDisciplinas.py

    ports:
      - 5003:5000

    depends_on:
      - db
 
    environment:
        MYSQL_PASSWORD: 'root'

    networks:
      - redecomum

#-------------------------------------------------------------------------------------------------------------

  regmatdisc:
    container_name: registrar_matdisc

    build:
      context: Base/Classes
      dockerfile: DockerfileRegMatDisci
      args:
        FLASK_APP: RegMatDisci.py

    ports:
      - 5007:5000

    depends_on:
      - db
 
    environment:
        MYSQL_PASSWORD: 'root'

    networks:
      - redecomum

#-------------------------------------------------------------------------------------------------------------

  reguser:
    container_name: registrar_usuario

    build:
      context: Base/Classes
      dockerfile: DockerfileRegUser
      args:
        FLASK_APP: RegUser.py

    ports:
      - 5005:5000

    depends_on:
      - db
 
    environment:
        MYSQL_PASSWORD: 'root'

    networks:
      - redecomum

#-------------------------------------------------------------------------------------------------------------
  
  dbAlunos:
    container_name: dbAlunos

    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - 6000:3306
    
    volumes:
      - dbAlunos:/var/lib/mysql
      - ./DataBase/alunosDB.sql:/data/application/alunosDB.sql
    

    networks:
      - redecomum

#-------------------------------------------------------------------------------------------------------------
 
  dbDisciplinas:
    container_name: dbDisciplinas

    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - 6000:3306
    
    volumes:
      - dbDisciplinas:/var/lib/mysql
      - ./DataBase/disciplinasDB.sql:/data/application/disciplinasDB.sql
    

    networks:
      - redecomum

#-------------------------------------------------------------------------------------------------------------
 
  dbUsers:
    container_name: dbUsers

    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - 6000:3306
    
    volumes:
      - dbUsers:/var/lib/mysql
      - ./DataBase/usersDB.sql:/data/application/usersDB.sql
    

    networks:
      - redecomum

#-------------------------------------------------------------------------------------------------------------
 
  dbAlunosDisciplinas:
    container_name: dbAlunosDisciplinas

    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - 6000:3306
    
    volumes:
      - dbAlunosDisciplinas:/var/lib/mysql
      - ./DataBase/alunos_disciplinasDB.sql:/data/application/alunos_disciplinasDB.sql
    

    networks:
      - redecomum

networks:
  redecomum:

volumes:
  dbAlunos:
  dbDisciplinas:
  dbUsers:
  dbAlunosDisciplinas: